service: api-rest-aws-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_ENV: production
    # DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}

functions:
  api:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

# resources:
#   Resources:
#     DynamoDBTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: ${env:DYNAMODB_TABLE}
#         AttributeDefinitions:
#           - AttributeName: id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: id
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST

plugins:
  # - serverless-dotenv-plugin
  - serverless-offline

# custom:
#   dotenv:
#     path: ./config/.env